name: example
description: "O'Mesh Examples App - Showcaseing usage example on flutter"
publish_to: 'none'
version: 0.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mesh:
    path: ../
  mix: ^1.4.4
  syntax_highlight: ^0.4.0

flutter:
